### ISSUE TITLE
VSCODE Extension for ZX Spectrum Next - Export BIN .bas issue

### ISSUE THREAD

**Issue by Andy1966uk** [remy/vscode-nextbasic#1]
Hi Remy, not sure if you saw this in my Facebook PM. There appears to be an issue exporting bin .bas files from the VSC extension 1.01 version. On initiating the command via command palette, the prompt launches as expected for you to enter file name. However no new file is actually created....

**Comment by remy** [comment]
Cheers - I meant to file this - I know what it is, it's the weird windows path getting in the way (again).

<img width="594" alt="Screenshot 2020-05-12 at 15 49 56" src="https://user-images.githubusercontent.com/13700/81707005-3ed6de00-9468-11ea-97a1-aae3718d659a.png">

I'm using native vscode methods to get the path, so I'm now looking into _why_ it's wrong. 

The path it's (wrongly) trying to write to is:

```
/C:/CSPECT/…/file.bas
```

I'm guessing the `/C:/` bit is wrong. If you were to move a file (any file) using vscode (using the palette ctrl+shift+p / move), what path do you see? And does the move inside vscode work?

**Comment by remy** [comment]
The fix for this is going up in 1.1.0 which should be available in about 10 minutes in vscode. Thanks for the report 👍

**Comment by Andy1966uk** [comment]
Cheers, really finding your tools useful, especially the Sptite / TileMap tool.... keep up the good work...

**Comment by Andy1966uk** [comment]
All working, tested exported binary on CSPECT and on Next HW, all good.
