### ISSUE TITLE
Error tokenizing BEEP (i suppose)

### ISSUE THREAD

**Issue by jsanjose** [remy/vscode-nextbasic#10]
Another problem with the tokenizer. This time is with BEEP, I think.

Trying the "breakout.bas" demo that comes with Next it gives always "Nonsense in BASIC" just in the lines where there is a BEEP.

Using dot command "txt2bas" it works right.

Attached is the program for you to try.

[breakout.bas.txt](https://github.com/remy/vscode-nextbasic/files/4696370/breakout.bas.txt)

**Comment by remy** [comment]
thanks 👍

**Comment by remy** [comment]
Change going up to the vscode marketplace shortly.
