### ISSUE TITLE
Definition of sprite incorrect - minor

### ISSUE THREAD

**Issue by StevenPowley** [remy/vscode-nextbasic#12]
Tooltip shows definition as sprite s,x,y,i,f and text says "sets sprite f to..." this should read sets sprite s

**Comment by remy** [comment]
The text is directly from the specnext wiki, here: https://wiki.specnext.dev/NextBASIC#Sprites

Happy to take an edit

**Comment by StevenPowley** [comment]
Seems the mistake is at source. It clearly makes no sense as repeats f in
the definition for both sprite and flags. Which is definitely wrong. The
first parameter is certainly sprite number and therefore s. I felt critical
posting it as minor. Thanks for listening to my ramblings.

Steve.

**Comment by remy** [comment]
Totally fine to post issues on this - it was scraped and honestly I wasn't even sure whether to included it - but I've found it useful once or twice.

I'll re-read the paragraph and [update it](https://github.com/remy/vscode-nextbasic/blob/master/nextbasic.json#L112).
