### ISSUE TITLE
PEEK$ is not recognised

### ISSUE THREAD

**Issue by kounch** [remy/vscode-nextbasic#15]
PEEK$ is misunderstood as an hex number.

![peek$](https://user-images.githubusercontent.com/338620/84523588-d2563580-acd8-11ea-99f1-cb0a41dabb51.png)

**Comment by kounch** [comment]
PEEK$ is misunderstood as an hex number.

![peek$](https://user-images.githubusercontent.com/338620/84523588-d2563580-acd8-11ea-99f1-cb0a41dabb51.png)

**Comment by remy** [comment]
If you're poking around, then ignore this - but if the validation is getting in the way (with invalid errors), you can disable it in the extension settings.

**Comment by kounch** [comment]
I have been ignoring it for some time know, but thought that it would be good to tell you, just in case.

Thanks

**Comment by remy** [comment]
Yeah, please do drop any validation errors you see my way. I think I've bitten off more than I wanted to chew trying to replicate NextBASIC's parsing algo for validation and error hinting (the int parsing is super tricky…for me!)
