### ISSUE TITLE
Feature request / Syntax detection

### ISSUE THREAD

**Issue by Andy1966uk** [remy/vscode-nextbasic#17]
Just a quick one. I am using custom Proc i.e. DEF PROC DisplayBadGuy1 and it doesn't get detected as a subrouteine in blue. It works, so not a big issue, but any PROC where there is a number, doesn;t get recongnised... thx

**Comment by remy** [comment]
Shouldn't it be `DEFPROC DisplayBadGuy1`? Certainly the syntax highlighting will work without the space, but it's possible that NextBASIC let's it fly with a space (apparently spaces are valid charactes in variable names which has kind of broken my brain!)

**Comment by remy** [comment]
Did you get to the bottom of this in the end?

**Comment by remy** [comment]
Going to mark as a non-issue - I'm guessing it's fine.
