### ISSUE TITLE
When using sub directories, CSPECT seems to duplicate folders, as part of copy process...

### ISSUE THREAD

**Issue by Andy1966uk** [remy/vscode-nextbasic#19]
I am using sub folder, i.e. LOAD "procbanks/ProcsBank40.bnk" BANK %40  , but on CSPECT I get the "probanks" directory created, with another "Procbanks" folder within it, and it's this one that my bank files end up in...  Some where is copying over the content to CSPECT there is a directory issue and not sure it's me or the tool... will PM in FB images

**Comment by remy** [comment]
Fixed in latest release - 1.4.4

Thanks as always 👍
