### ISSUE TITLE
Feature Request - Renumbering

### ISSUE THREAD

**Issue by Andy1966uk** [remy/vscode-nextbasic#2]
Would it be possible to consider adding a renumbering facility ?

**Comment by remy** [comment]
I've been working on one already. I've got renumbering working at a basic level, but I really want to be able to _relocate_ code, so take lines 100-120 and relocate it to line 20 and it would push down all the lines from 20 onwards to make space - whilst maintaining goto numbers correctly (!)

**Comment by Andy1966uk** [comment]
1.33 seems to be broke. Was just on 1.32, updated to 1.33 and I get the error nextbasic.run can't be found

**Comment by Andy1966uk** [comment]
Thanks, renumbering works :)

**Comment by Andy1966uk** [comment]
Sorry 1.33 still  broke, but tried to close renumbering case which was working in 1.32...

**Comment by remy** [comment]
Sod, I'll fix it - thanks for the heads up

**Comment by remy** [comment]
Just to confirm - is this the single line shift renumbering or the full document renumber?

**Comment by Andy1966uk** [comment]
it's the Nextbasic.run that has the issue, the renumbering you implemented in the 1.32 was fine... I just tried to close the request related to that.... the run issue is really what i wanted to highlight... renumbering also appears bust in 1,33

**Comment by Andy1966uk** [comment]
In summary it all worked in 1.32, now it can;t find the commands, error..

**Comment by remy** [comment]
Fix inbound - 1.3.4 should be available in a couple of minutes.

**Comment by Andy1966uk** [comment]
cheers, sorry for the confusion. I was trying to report the one issue and close the original feature request for renumbering.... all your tools are key to my project :) thx

**Comment by remy** [comment]
No problem - I've just switched to using `#autoline` in my code, and in trying to add compatibility I hosed the entire plugin 😆 your report caught that 👍

**Comment by Andy1966uk** [comment]
All works now, thanks :)
