### ISSUE TITLE
Issue with Integer Variable in 1.4.5

### ISSUE THREAD

**Issue by Andy1966uk** [remy/vscode-nextbasic#23]
Hi Remy,

Just upgrade to 1.4.5 , and my code is showing errors..

eg. %x=255    where integer variable are declared, the % is highlighted as an error. Where ever I declare an integer variable shows the error...  " Integer expression should be the start of an argument, "%" "   
On their own lines it's ok, but I have them all over as required by my code. Ran ok Yesterday and on Real HW... thx

Another use case...

IF Walk=1 THEN IF %x <= 42 THEN IF View=1 THEN MapSection=MapSection-1: **%x=255** :r=r-262: PROC MapDetection()

This was ok in previous build. thx

**Comment by remy** [comment]
Is the whole line that (besides the line number - or not if you have
autoline turned on)?

**Comment by Andy1966uk** [comment]
Not using autoline at all...

Where ever in my code where I declare the integer variable is the issue, unless it's at the start of a line.... previous version was ok...

**Comment by Andy1966uk** [comment]
the error just highlight the % as the error...

**Comment by remy** [comment]
This is what I'm seeing… this is… unexpected.

<img width="676" alt="Screenshot 2020-07-17 at 08 18 18" src="https://user-images.githubusercontent.com/13700/87759373-1f608680-c806-11ea-9ed0-71aeaa2d3850.png">

**Comment by Andy1966uk** [comment]
not using autoline, just posted two images in FB messenger, not sure how to post image here

**Comment by remy** [comment]
Able to replicate, it's only after a separator:

```
30 PRINT "ok":%x=255
``

**Comment by remy** [comment]
(posting images here - drag and drop into the edit area :) but it's cool - I've got the bug now)

**Comment by Andy1966uk** [comment]
at start of line it's on i.e   
%r=255 , but when used in between : the error shows..... was ok yesterday

**Comment by remy** [comment]
Fix inbound.

**Comment by remy** [comment]
That's gone up to the extension market place now. I also fixed that annoying bug where cspect wouldn't lunch if there was a validation error (usually incorrect) - not sure how that crept in.
