### ISSUE TITLE
Toggling line comment leaves extra space if using semi-colon

### ISSUE THREAD

**Issue by Guddler** [remy/vscode-nextbasic#24]
As title really. If you have the default of 'REM' set them commenting a line and then uncommenting is fine. If you instead change it to semi-colon then when you comment '; ' is inserted but toggling again removes only the semi-colon, leaving the spurious space behind. Repeating this 10 times will result in 10 new spaces at the start of the line (I know, you wouldn't really do that!).

**Comment by remy** [comment]
Damn, yeah, spotted that myself.

I'll sort that out, it was annoying me but figured until someone reported it, I'd live with it. Now I'll fix it 😊

**Comment by remy** [comment]
That's fixed and live in the latest version of the extension. Default behaviour for vscode is to auto-update, so you should have the fix now or shortly.

Thanks again.
