### ISSUE TITLE
PLOT OVER 1 ; returns an error

### ISSUE THREAD

**Issue by Tailzer** [remy/vscode-nextbasic#26]
if you add the OVER 1 command to PLOT followed by semicolon it causes the extension to think there is an error? 
This is the code that created the error.
5 LET x=0
10 LET t=0.1
20 IF INKEY$="p" THEN GO TO 35
30 GO TO 10
35 LET x0=x
40 LET x=x+t
45 IF x>=255 THEN LET x=0
50 PLOT OVER 1;x0,0: PLOT x,0
55 LET t=t+.2
60 GO TO 20
![image](https://user-images.githubusercontent.com/2272490/92964331-d32f6c80-f46b-11ea-855c-1d7552568f0d.png)

**Comment by remy** [comment]
Thanks for the code, exactly what I need to replicate and fix. 

I'll get this sorted early next week (it's my bday this w/e so trying hard to keep away from the computer!).

**Comment by remy** [comment]
Hmm, I can't replicate this - both in my install of VS Code and with the core validation logic (though I know I very recently fixed a similar validation issue).

The latest NextBASIC vscode extension is version 1.5.2 - can you confirm the version you're on?

**Comment by Tailzer** [comment]
the version said 1.5.2 but also said reload required, I had a similar issue tonight with PLOT INVERSE 1;132,122 but that went after the reload. Sorry I guess i was on a previous version. Confirmed working as it should on 1.5.2 for both the errors I saw.
