### ISSUE TITLE
Running Cspect on mac

### ISSUE THREAD

**Issue by jaymundy** [remy/vscode-nextbasic#32]
Geraldines-MacBook-Pro:cspect2_11_1 geraldinemundy$ ls
3xAY			Mouse			cspect-next-2gb.img
Beast			NXtel.bat		dll_src
CSpect.exe		NXtel.nex		enNextZX.rom
CSpectReadme.txt	OpenTK.dll		enNxtmmc.rom
DMA			OpenTK.dll.config	parallax.bat
Layer2			SNASM.rtf		parallax.nex
LowResDemo		ay8912.dll		snasm.exe
Geraldines-MacBook-Pro:cspect2_11_1 geraldinemundy$ 

...... now what?

Can I run cspect from here just by typing cspect.exe? I've already installed mono from the link shown if vscode. How to run cspect on a mac?

**Comment by jaymundy** [comment]
OK if i type mono cspect.exe -w4 -vsync -s28 -60 -tv -basickeys -zxnext -nextrom it tries to open a window but it's all black and the mouse is frozen.  Now trying to work through this section of specnext tutorial:

https://specnext.dev/tutorials/cspect-mac/
"Ok, I’ve done all that and it works but the mouse is giving me trouble!"

**Comment by remy** [comment]
The mouse doesn't work in cspect. It's some bug that's not been fixed in a while. Best to just keep clear of it.

Where did you get up to? Can you launch cspect so that you can using the next browser - ie. The same menu you'd see on the hardware?

**Comment by jaymundy** [comment]
Hey Remy, if I had any hair I'd be pulling it out. Wow what a cruncher. So far I can launch cspect from the command line using: mono cspect.exe -w3 -basickeys -zxnext -nextrom -mmc=cspect-next-4gb.img
... but I had to use the 4gb rom image. The 2gb image just seemed to open a regular (non Next) emulator which didn't work right (only allowed a couple sporadic keyword entries then froze). I also got an error when running the 4g img version saying enNextMF.rom was missing so I found it in github and put it in the cspect folder.
Now when I run cspect using the command above it shows the Next opening screen but freezes until I click on it with the mouse then the mouse freezes and I have to press command tab a few times to jump around and back again and try double clicking on the emulator (with the mouse frozen in the corner) then the emulator window then gets a bit bigger (elongates horizontally with black to the left and right of the emulator screen) and seems to allow me to browse the folders and run games and stuff (seems to work properly in other words) but I can't make the window any bigger since the mouse is frozen. Trying the procedure to reposition the window to fix the mouse problem using the instruction from specnext.com to create an apple script gives me an error message.
Trying to run a program from vscode gives me hdfmonkey error message:
hdfmonkey put failed (possible bad path to hdfmonkey):
/bin/sh: /Users/geraldinemundy/Desktop/ZXSpecNextDev/CSpect2_12_36/hdfmonkey.exe: Permission denied

:'(

**Comment by jaymundy** [comment]
Ok so got cspect working by increasing the screen size parameter to 6, immediately maximizing the cspect window as soon as it opens then pressing command tab twice To jump out and back (otherwise it freezes). Thus seems to get cspect all working. Now just need to sort out the hdfmonkey thing .....

**Comment by remy** [comment]
I posted how to run hdfmonkey in the other thread you started. The short version is you're trying to run the windows version of hdfmonkey on your Mac.

Cspect is windows, but it's been written specifically to be compatible with a program called `mono` which lets you run it on a Mac.

**Comment by remy** [comment]
From facebook I gather you're all good - so I'm going to go ahead and close these two issues 👍
