### ISSUE TITLE
Installing hdfmonkey on mac

### ISSUE THREAD

**Issue by jaymundy** [remy/vscode-nextbasic#33]
INSTALLING
----------
From a tarball (see http://files.zxdemo.org/gasman/speccy/hdfmonkey/):

    tar xzf hdfmonkey-0.4.tar.gz
    cd hdfmonkey-0.4
    ./configure
    make
    sudo make install

From git:

    git clone https://github.com/gasman/hdfmonkey.git
    cd hdfmonkey
    autoheader
    aclocal
    autoconf
    automake -a
    ./configure
    make
    sudo make install

From git into a Debian source package:

    git clone https://github.com/gasman/hdfmonkey.git
    dpkg-source -b hdfmonkey

From git into Debian binary package:

    git clone https://github.com/gasman/hdfmonkey.git hdfmonkey-0.4.1
    cd hdfmonkey-0.4.1
    fakeroot debian/rules binary

==========================
... above are the installation instructions from the github link.... how to install on mac.  I tried installing it somehow but keep getting hdfmonkey put failed error (possibly permission denied?)  when selecting 'Run with cspect' from vscode.

This is the error I get:
hdfmonkey put failed (possible bad path to hdfmonkey):
/bin/sh: /Users/geraldinemundy/Desktop/ZXSpecNextDev/CSpect2_11_1/hdfmonkey.exe: Permission denied

**Comment by remy** [comment]
Okay, so:

1. Download this URL: http://files.zxdemo.org/gasman/speccy/hdfmonkey/hdfmonkey-0.4-osx.zip
2. Unzip and move the file `hdfmonkey` into your home directory (or even `/use/local/bin` - but do what's easiest to you)

That's hdfmonkey installed. 

Now in the extension, you need to enter the *full path* to hdfmonkey. So if my home directory is `/Users/remy` and hdfmonkey is in there, the full path is `/Users/remy/hdfmonkey`

**Comment by jaymundy** [comment]
OMG I can't believe it's actually working now after spending most of the day trying to figure it out.  Thank you so much!!!
Thanks also for posting this tutorial. This is gonna make my programming so much easier to be able to do it on the macbook instead of the Next hardware.  You rock!

**Comment by remy** [comment]
You're welcome 👍
