### ISSUE TITLE
Command 'nextbasic.run' not found

### ISSUE THREAD

**Issue by MightyAxle** [remy/vscode-nextbasic#39]
Hi

I am having problems running a simple program like :  

10 PRINT"HELLO WORLD"
20 GOTO 10

When the program is compiled via Visual Studio Code using NextBASIC it returns with an error (command 'nextbasic.run' not found)

I'm running everything on a PC and have the correct paths and arguments setup in the extensions settings whilst using NextBASIC 1.7.1

I had tried everything on two other Laptops using Windows 10 and I get the same results.

Any advice would be great! 

Many thanks.

**Comment by remy** [comment]
Hi there - you caught me at christmas so I was off the machine.

Out of the gate it sounds like there's some serious problems. Can I ask first to a fullscreen screenshot and share it here so I can see what you see? 

I'm specifically looking to see if the language has been enabled as per this:

<img width="987" alt="Screenshot 2020-12-27 at 20 15 01" src="https://user-images.githubusercontent.com/13700/103179079-4d9bc500-4880-11eb-98b9-75c6d140ef52.png">

**Comment by MightyAxle** [comment]
Thank you for getting back to me. 

Suddenly, as I changed the Language and checked all the settings again, including the one 'settings.json', everything worked! 😊

I wouldn't have thought to check the Language setting.

Thank you for your time.

Many thanks. 

![image](https://user-images.githubusercontent.com/76586863/103179762-21377700-4887-11eb-8dfe-8b6379264d16.png)

**Comment by remy** [comment]
Ah, that explains it. The commands are language specific, so if you're not in NextBASIC language, vscode doesn't try to load or run the NextBASIC commands.

Glad it's sorted though.
