### ISSUE TITLE
Renumbering a section in Windows, doesn't appear top work.

### ISSUE THREAD

**Issue by Andy1966uk** [remy/vscode-nextbasic#4]
Renumbering a section doesn't work (or how you select the lines to renumber) .
Renumbering whole program, works fine, it's just when you try section it does nothing...

**Comment by remy** [comment]
Ta - known limitation, mostly around the fact I don't know what the UI would be at the moment. i.e. it's fine to select a range then renumber, but what if the final number overlaps with the first line after the selection? Which is when it needs user input… just haven't solved it in my head yet.

Very guiltily I've moved all my NextBASIC across to using `#autoline` which means I can't use `GO TO` or `GO SUB` but I can forget about squeezing lines around! :)
