### ISSUE TITLE
Export to .BAS causes errors with new NextZXOS 2.08 integer syntax

### ISSUE THREAD

**Issue by KevReillyUK** [remy/vscode-nextbasic#41]
For now this is technically an edge case observation rather a bug, as it deals with pre-release code, but as KS2 gets closer it might become a problem once 2.08 becomes the official baseline.

Under NextZXOS / NextBASIC 2.08 the following code snippet...
```
10 %a = 1
20 PRINT (%a) + 1
```
...should yield the output "2", but instead gives "1" and _N Statement Lost, 20:1_ if exported from VS Code. The BASIC file ends up 6 bytes shorter than it should be, suggesting that maybe the binary representation of the constant is not getting translated properly.

There is a post with some more details in the NextBASIC Facebook group [here](https://www.facebook.com/groups/ZXNextBasic/posts/1651238025402530/).

**Comment by remy** [comment]
Only took 6 months to reply, but fixed and live 😆 (thanks for reporting either way)
