### ISSUE TITLE
New version of NextBasic

### ISSUE THREAD

**Issue by nljorgenj** [remy/vscode-nextbasic#43]
Hello!

First of all I want to thankyou for the NextBasic plugin for VS-Code. It's great. Now on to my question:

From version 22.10a of the NEXT ZX OS they have added support for labels in the Basic language. 

Do you have plans to update your NextBasic VS-Code plugin?

BR
Jörgen

**Comment by remy** [comment]
Late to reply, but this support is now live in the extension, v1.10.0 👍
