### ISSUE TITLE
How to GOTO when #autoline used

### ISSUE THREAD

**Issue by BozRetro** [remy/vscode-nextbasic#44]
Hi there!

Great extension for VSCode..., thank you Remy for putting it all together!

Quick (and probably dumb) question; When I use the \#autoline command, how do I know where to GOTO when I need to? The "hard way" of course is to count the number of executable lines and "do the maths", but is there an easier way of referencing lines? Maybe I've missed some documentation somewhere...

Cheers,
Boz.

**Comment by BozRetro** [comment]
Solution found.

**Comment by remy** [comment]
Might be useful to share the solution you found (just for other), but pleased you're sorted either way.

**Comment by BozRetro** [comment]
Good idea, remy :)  Labels, basically. Introduced in 2.08:

myLabel:
PRINT "Hello forever! ";
GO TO myLabel
