### ISSUE TITLE
v1.11.0 #bank BANK20 gives error "A system error occurred (EROFS: read-only file system, open 'BANK20')"

### ISSUE THREAD

**Issue by NealeTools** [remy/vscode-nextbasic#46]
Code:
#bankfile BANK20
`10 "Hello World"`

<img width="444" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/e500b560-71cc-4297-b665-cd4fc11b679b">

**Comment by remy** [comment]
Has the file been saved yet, and is this from run or export?

**Comment by remy** [comment]
I'm able to replicate with "run" (I did test this last night, but it was late!!!)

**Comment by remy** [comment]
Sod, I forgot to update the txt2bas dependency which fixed this (which explains why I found and fixed this last night).

That's fixed in 1.11.1

**Comment by NealeTools** [comment]
Thanks! Will try out later :-)
