### ISSUE TITLE
PRINT POINT encoding bug

### ISSUE THREAD

**Issue by NealeTools** [remy/vscode-nextbasic#49]
5 %i=5
10 DIM s$(10,20)
20 PRINT s$(%i,1 TO 10)
30 PRINT POINT %i<<3,%i;s$(%i,1 TO 10)

Fails on line 30.
In case it helps, small mods that pass:
30 PRINT POINT %i,%i;s$(%i,1 TO 10)
30 PRINT POINT %i<<3,%i;s$(%i)

Tested on v1.11.1 (integer slicing is a 2.08/.09 addition).

**Comment by remy** [comment]
I've got a fix in the wings for this (and your LAYER issue too) - both related to the same parsing problem.

**Comment by NealeTools** [comment]
Hi Remy. Was this fixed? I have a similar issue in v1.11.3:
10 PRINT AT %1,%29;%840/PEEK 23672
Gives Nonsense in BASIC. This used to work fine on earlier VSCode versions.
Removing the integer % before 840 avoids the error.
<img width="537" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/a36e9860-7d3c-4379-816f-a38792d28366">

**Comment by NealeTools** [comment]
@remy Is this fixed as well?
10 PRINT AT %1,%29;%840/PEEK 23672
