### ISSUE TITLE
OPEN # doesn't tokenize right

### ISSUE THREAD

**Issue by jsanjose** [remy/vscode-nextbasic#5]
I've been testing the "windowsChannels" demo that comes with the Next.

Running from "run with cspect" this line gives error:

`40 OPEN #4,"w>4,0,16,20,5"`

This is because, when it's tokenized to BAS it translates to:

`40 OPEN # #4,"w>4,0,16,20,5"`

This doesn't happens with the dot command "txt2bas" that comes with the Next.

**Comment by remy** [comment]
Thanks - I'm sure I saw that before, so I must have reintroduced it. I'll try to get a fix out this evening because it affects launching into cspect too.
