### ISSUE TITLE
10 PRINT AT %1,%29;%840/PEEK 23672

### ISSUE THREAD

**Issue by NealeTools** [remy/vscode-nextbasic#52]
v1.11.4 (and also in prior versions)
10 PRINT AT %1,%29;%840/PEEK 23672
The % before 840 leads to NONSENSE in BASIC.
Remove the % and it is parsed OK.
(I added this to another issue, but I think it was not picked up).

**Comment by remy** [comment]
These are parsing bugs in my code in the remy/txt2bas repo.

Cheers for testing and finding these (it's unrelated to the POINT issue you found before, which was to do with the `;` in the statement).

**Comment by NealeTools** [comment]
This appears fixed in v1.11.6 - thanks! 👍
