### ISSUE TITLE
Auto run of Index.bat fails from 1.11.0 onwards

### ISSUE THREAD

**Issue by Andy1966uk** [remy/vscode-nextbasic#54]
Up until v 1.11.0 of this extension, the basic program was launch via the autoexec.bat correctly with the index.bat.

For some reason with newer versions up till the latest 1.11.5, when RUN with CSPECT, the NEXT menu come up, but the basic program isn't launched. 
I tried with a simple program however, and it works fine. 
CSPECT is CSpect2_19_4_4
NXOS 2.08

Can you think of anything that changed from 1.11.0 to 1.11.1 that might effect the auto starting of a program in CSPECT ?

**Comment by Andy1966uk** [comment]
[TirNaGog_0.947_RC1.zip](https://github.com/remy/vscode-nextbasic/files/14780804/TirNaGog_0.947_RC1.zip)
My FULL program/game here if you want to test / check some time....

**Comment by Andy1966uk** [comment]
<img width="1910" alt="Screenshot 2024-03-27 202335" src="https://github.com/remy/vscode-nextbasic/assets/64156039/4aad8227-5fe0-4629-abdd-edcf4f37f02a">

**Comment by remy** [comment]
ACK. I'm looking into this for you today (probably later though/after work)

**Comment by remy** [comment]
I'm pushing an update to the extension in a moment.

**Comment by Andy1966uk** [comment]
Not urgent at all. Enjoy Easter Remy, it can wait thx

**Comment by Andy1966uk** [comment]
@remy Thanks, works perfectly now
