### ISSUE TITLE
Lack of white space between @ and next char in labels

### ISSUE THREAD

**Issue by pruebaoscar** [remy/vscode-nextbasic#55]
Hi Remy! How are you? I'm using your vscode extension for nextbasic and I think that I've found a little bug with @ used as label. When I use it, for example: 

10 LOAD "sprites2.spr" BANK 12: SPRITE print 1 : SPRITE BANK 12
20 x=32
30 @ here: x+=1 : SPRITE 0,x,64,1,1 
40 GO TO @ here

VSCode send to CSpect the code without space between @ and 'here' characters and NextBasic launch an error: C, nosense in basic, 30:1
Once in CSpect if, in the sent code, I add a space between @ and 'here' it works fine.

Thanks for your work.
Best regards

**Comment by remy** [comment]
Thanks for filing, I'll get this (hopefully) resolved, this week 👍

**Comment by remy** [comment]
note to self: the parser is treating `@` as a binary number with no value…

**Comment by remy** [comment]
Fixed in latest release 👍

**Comment by pruebaoscar** [comment]
Hi Remy, just tested and works perfect!
Thank you!
