### ISSUE TITLE
Export fails due to parsing bugs (examples in thread):

### ISSUE THREAD

**Issue by NealeTools** [remy/vscode-nextbasic#59]
v1.11.7
There are a few parsing bugs that pass OK into RunInCSpect, but are picked up as errors in Export (and cause export to fail).

Examples:

%CODE:
<img width="359" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/1b810d1a-1452-4dce-a016-3f192b19fa9e">

ERROR$:
<img width="369" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/69db4f02-e58b-42aa-b5ff-b4b6f1ab4fe1">

IF %SPRITE AT (j,1)>127 THEN SPRITE CONTINUE %j,,%SPRITE AT (j,1)-(i*i[0]) TO %239 STEP %SGN{-i[0]} RUN
(I think this is referring to both the "TO %239" and "%SGN{-i[0]}" parts, both of which are valid syntax and actually encode fine I think it i just the error stops the export.
<img width="360" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/11a3082e-c058-4135-bd43-497d7d102a6d">

**Comment by remy** [comment]
Note to self: I need to merge the logic from the parser across to the validation (specifically subStatement int logic)

**Comment by NealeTools** [comment]
Bump: example 2 and 3 still fail export in v1.11.8

**Comment by remy** [comment]
Yeah, this is validation, as per my comment, I need to make time to merge the logic from the new parsing to the validator (not a simple process)

**Comment by NealeTools** [comment]
In the short-term could you just turn off the validator? The code compiles and runs fine in CSpect, so the tokenisation is OK, but export never happens due to the check, so I cannot test any export functionality etc. :-)

**Comment by remy** [comment]
yep - you can disable it from the settings ("Perform custom inline NextBASIC validation" - uncheck that)

**Comment by NealeTools** [comment]
Great! My apologies for not realising what this option did! 🫣

**Comment by NealeTools** [comment]
Hi @remy : Unfortunately, unticking this option does not allow the export to complete. I can see that the red underline no longer is present, but the file does not build if there are any syntax errors. This prevents me exporting to test on HW via NextSync, which is an essential part of my workflow now because I am using some HW features that CSpect does not support - thanks!
<img width="990" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/a783ffff-c0b0-4076-9086-3d4818be434c">

**Comment by remy** [comment]
I'll sort this. That checkbox is primarily there to disable validation
across the board and allow export even when my (wrong) validation fails.

**Comment by NealeTools** [comment]
@remy Apologies for the nag, but is there any quick fix for turning off the validation on export? I feel like the new parser is 99% there! :-)
The validation check is currently preventing me from exporting working code as multiple .bank sections—or indeed exporting any code for test on HW. Thanks!

**Comment by remy** [comment]
I'm snagging early morning time to get these done.

Any chance you have a snippet of the code that's causing this. I'm reviewing the code and it "says" it's not validating by default, so I wonder if I'm missing something else...

**Comment by NealeTools** [comment]
IF %SPRITE AT (j,1)>127 THEN SPRITE CONTINUE %j,,%SPRITE AT (j,1)-(i*i[0]) TO %239 STEP %SGN{-i[0]} RUN

**Comment by NealeTools** [comment]
Also %CODE and ERROR$ get underlined.
They pass "run in CSpect", so get encoded correctly, but the syntax checker flags them (red underline) and stops the Export script.

**Comment by NealeTools** [comment]
Actually, %CODE seems OK now, but ERROR$ is underlined and fails:
<img width="1324" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/152dc8ac-875a-433c-a14b-265041e633c1">

**Comment by NealeTools** [comment]
Here is the another one:
<img width="1365" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/d8fdf688-e22d-4ded-8079-d6c24ea5c5f2">

**Comment by remy** [comment]
Found the code now, it says the default is false, but somehow I changed the default much deeper down to true 🤦

**Comment by remy** [comment]
Okay, v1.11.1 (all the ones) disables validation during export. Sorry that took so long.

**Comment by NealeTools** [comment]
Thanks Remy! I can confirm the export now works (syntax still underlined in red when enabled).

I'll try out bank exports next and hopefully there won't be any further headaches I unearth! :-)
