### ISSUE TITLE
First line of code it's deleted when tokenizing

### ISSUE THREAD

**Issue by jsanjose** [remy/vscode-nextbasic#6]
If I write a program like this and run with "run with cspec" the first line is missing when tokenizing it to BAS:

```
10 PRINT "HELLO"
20 PRINT "WORLD"
30 GOTO 10
```

It only prints "WORLD" many times because line 10 is missing in the generated BAS.

**Comment by remy** [comment]
Hmm, this is weird. I just tried to replicate and it was okay, so there's something going with your setup that my code is getting confused with - that's to say: it's broken for you (and probably others), so let's find out why.

<img width="601" alt="Screenshot 2020-05-26 at 18 29 04" src="https://user-images.githubusercontent.com/13700/82931450-dbc46b80-9f7e-11ea-8cae-e566a0f3d8f2.png">

Can you let me know:

- What version of NextBASIC extension you're using?
- What operating system you're using (and possibly version)
- Add any extra information about your dev environment

**Comment by jsanjose** [comment]
NextBASIC version 1.3.5
Operating system: Windows 10

Attached a screenshot of the NextBASIC config.

![nextbasic-config-jsj](https://user-images.githubusercontent.com/11646970/82932290-78d7d200-9f88-11ea-9010-d9c7d6f34a15.png)

**Comment by jsanjose** [comment]
Also this is a screenshot showing the problem.

![run-test-nextbasic](https://user-images.githubusercontent.com/11646970/82932439-b50b3280-9f88-11ea-87ae-d4d2cfeddfc7.png)

**Comment by jsanjose** [comment]
Also if it helps you I'm also sure that it worked right in the previous version.

**Comment by remy** [comment]
Thanks. One extra question, are you able to connect to the Cspect image and upload the file in `/devel/index.bas` - it's the NextBASIC file that's generated on the fly and it might have some clues in the file (but make sure you've not saved it inbetween in the native NextBASIC editor).

**Comment by jsanjose** [comment]
Sure, here you have it attached.

[index.zip](https://github.com/remy/vscode-nextbasic/files/4684357/index.zip)

**Comment by remy** [comment]
And to confirm, this happens consistently? i.e. you've got it on any file, it has nothing to do with line `10` or anything (not that I can see how it would be).

There's nothing that jumps out at me, so I'm trying to think how VS Code would be giving the extension only _part_ of the file…

Actually, could you zip up your source .txt file and post that too? Just to rule out any encoding in the source.

**Comment by remy** [comment]
I'm struggling to find where this is happening my code. Another test that might be useful, can you run the `NextBASIC: export to binary .bas` against your text file and send the resulting .bas file?

**Comment by jsanjose** [comment]
Here it is the resulting .bas from "export to binary .bas". Amazingly this one works well if I copy it to the virtual SD card of the CSpect.

[test.zip](https://github.com/remy/vscode-nextbasic/files/4686986/test.zip)

**Comment by remy** [comment]
This is good, and suggests the problem is in the vscode extension (and not in the underlying txt2bas logic), and it also means it's in the auto-run logic, so I know where to look. The bad news is I can't see anything that stands out, so I'll have to dig deeper and probably fire up the windows machine to see if I can replicate.

**Comment by remy** [comment]
Am able to replicate on a windows machine (with lunch!)

**Comment by jsanjose** [comment]
Nice! So seems only a problem in the Windows version of VScode.

**Comment by remy** [comment]
Found the bug and getting a fix ready.

**Comment by remy** [comment]
Extension version: 1.3.9 will have the fix - going live now.

**Comment by jsanjose** [comment]
Working now! Nice!
