### ISSUE TITLE
BANK %27 DPOKE %y<<1,%BANK 27 DPEEK (319-n<<1)

### ISSUE THREAD

**Issue by NealeTools** [remy/vscode-nextbasic#61]
v1.11.7
BANK %27 DPOKE %y<<1,%BANK 27 DPEEK (319-n<<1)
Also encodes incorrectly (but fine once re-entered in ZXOS 2.08).

(Error seems to be caused by the "%" after the comma (but this is essential because the whole part is an integer expression.)

**Comment by NealeTools** [comment]
Hi Remy, Just wondering if these issues are still on your radar for a fix? Thanks!

**Comment by remy** [comment]
On my radar, just need to carve the time.

**Comment by remy** [comment]
Just for me, it's this part that's bad: `%BANK 27 DPEEK (319-n<<1)` - the statement is an integer expression, but once in the parens, the number is treated as literal (instead of int) - which causes the parse error.

**Comment by remy** [comment]
vscode extension 1.11.8 has all these fixes. Very wary I've refactored the int logic, but there's over 200 tests, so I'm hoping there's on regressions.

**Comment by NealeTools** [comment]
Thanks. Testing...
