### ISSUE TITLE
v1.11.11 Import to BANK failing - missing last lines (edited)

### ISSUE THREAD

**Issue by NealeTools** [remy/vscode-nextbasic#65]
Repro1:
9000 DEFPROC Init(): RUN AT %3: BORDER %0: PAPER %0: BRIGHT %1: INK %7: CLS: PALETTE OVER %0: LAYER %2,%0: LAYER %0: SPRITE CLEAR: SPRITE BORDER %1
9001 PROC LoadFont(): PRINT "LOADING METEOR X V 63 A COPC": PROC LoadPal()

Export to bank fails after the first line. I tried trimming, but cannot spot a pattern. However:

Repro2: (trimmed first few commands)
9000 PALETTE OVER %0: LAYER %2,%0: LAYER %0: SPRITE CLEAR: SPRITE BORDER %1
9001 PROC LoadFont(): PRINT "LOADING METEOR X V 63 A COPC": PROC LoadPal()

Both lines exports fine.

Note: The code above (and the encoding) works fine for RunInCSpect and regular export to .bas file. It is only not workign when I've tried to split or directly export these (and subsequent) lines into a banked section.

**Comment by NealeTools** [comment]
Repro3:
1000 PRINT "THIS IS A TEST"
1001 PRINT "THIS IS A TESTa"
1002 PRINT "THIS IS A TESTb"
1004 PRINT "THIS IS A TESTc"

The export fails after line 1002. (The fourth line does not get encoded, but I think the data is still in the final file in a binary form.)

**Comment by remy** [comment]
Just starting to look at this. I'm suspecting there's an encoding issue with the bank support, only because I can see the four line in the actual binary, but when I try to dump it back out, it's missing:

<img width="897" alt="SCR-20240709-qoyd" src="https://github.com/remy/vscode-nextbasic/assets/13700/fcebf9d9-237b-4845-8019-fdc2d41a02ae">

**Comment by remy** [comment]
@NealeTools can you remind me how to test this on the spectrum (my basic is rusty already!)

**Comment by NealeTools** [comment]
To test the bank output, type:
LOAD "MyBankedCode" BANK 20
BANK 20 MERGE
The latter command can only be typed in, not part of a program.

Alternatively, I think you could have a test program with:
10 LOAD "MyBankedCode" BANK 20
20 BANK 20 LIST

**Comment by remy** [comment]
<img width="705" alt="SCR-20240709-qqyy" src="https://github.com/remy/vscode-nextbasic/assets/13700/2bfbff5f-fe33-452b-8031-659efd7982ae">

<img width="705" alt="SCR-20240709-qqyy" src="https://github.com/remy/vscode-nextbasic/assets/13700/8e90b271-9872-442e-8027-e86a97762770">

I see it working (though I'll try your version now) - but my guess is that it still looses the last line in the import in VS Code.

Is it the Next that's the issue or VS Code?

**Comment by remy** [comment]
(fixed screenshot - wrong image went up)

**Comment by remy** [comment]
Might be my export process was different too - I'll check that.

**Comment by NealeTools** [comment]
Hmmm...Let me double-check my end.
I was suffering errors, and then, to troubleshoot, just using your online bas2txt converter to check the output. Now I am wondering if there wasn't a problem...and it was something independent!

I was exporting using the built-in exporter (Command+Shift+E) (or RunInCSpect), with the following #syntax:
#bankfile BankedProcs01
Which should, I thought, automatically generate a banked section as a separate file.
That's the one that I've been looking at/testing.

**Comment by remy** [comment]
Okay, I'll try using the `#bankfile X` directive. See if that's different.

**Comment by NealeTools** [comment]
I just tried (not using the bankfile directive): But using Export To bnk function from the palette:
<img width="653" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/83b79610-6bc4-45cc-987f-f85f16956f66">

**Comment by remy** [comment]
Yeah, import is definitely not right. So that's one bug, I want to make sure the source is actually correct for the Next though (I'm just testing too)

**Comment by remy** [comment]
Okay, the actual file is correct from my testing:

```
#program 65-test
10 PRINT "hello world."
20 LOAD "65-test.bnk" BANK 15
30 BANK 15 LIST
#bankfile 65-test.bnk
1000 PRINT "THIS IS A TEST"
1001 PRINT "THIS IS A TESTa"
1002 PRINT "THIS IS A TESTb"
1004 PRINT "THIS IS A TESTc"
```

Export to binary.bas, then push files to SD card. Then run `65-test.bas`:

<img width="705" alt="SCR-20240709-qurc" src="https://github.com/remy/vscode-nextbasic/assets/13700/ee9854b5-ab04-45e7-a03a-39c4edefc771">

---

I'll fix the import

**Comment by NealeTools** [comment]
Progress: There is a spurious character before line40:

<img width="594" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/dee73ba5-78d8-4ccc-bb39-363140b45973">

**Comment by remy** [comment]
@NealeTools strongly recommend hexfiend when looking at bytecode - excellent tool.

**Comment by NealeTools** [comment]
Definitely an extra opening bracket:
<img width="470" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/51259cfe-3472-46d9-9d1a-9d5e7da13151">

**Comment by remy** [comment]
Not sure what that is (atm) - but import is definitely dropping the last line. I can see the parser now failing.

Do you want to share both the plain text version of the source to the bank that made that file _and_ the `MyBankedProc01` file here?

**Comment by NealeTools** [comment]
I'm intrigued why your export looks OK?
Here they are: Note: I added the .txt suffix to permit upload.

[ExportTest.txt](https://github.com/user-attachments/files/16147745/ExportTest.txt)
[Test4.bas.txt](https://github.com/user-attachments/files/16147746/Test4.bas.txt)

**Comment by remy** [comment]
lol, the bracket you were seeing was line `40`.
<img width="1686" alt="SCR-20240709-rati" src="https://github.com/remy/vscode-nextbasic/assets/13700/b9a4f54c-ca81-42db-92b0-f1e018e0dff7">

I've got the fix for it clipping the last line (pretty sure all files should have been affected… or maybe it was a fluke that it wasn't).

I'll have to also get the web site synced because I know people do use that as a test, but it's released to in a totally different way.

**Comment by remy** [comment]
Just writing tests now to confirm fix (though the fix has thrown up something new already covered by the tests - which is a good thing)

**Comment by NealeTools** [comment]
So the export is OK? It could be another thing failing then (in the actual code). I may have jumped to a conclusion when I saw the output of the online txt2bas. Apologies if that was the case!
I'm actually finding that I'm getting a lot of bugs in BANKed code (even when banked by ZXOS itself) where it was fine when running in unbanked code.

**Comment by remy** [comment]
Right, worked out how it was never caught, it only affected bank importing (where the `type=3`, otherwise the logic was correct for `type=1` = program).

**Comment by remy** [comment]
Fix is going into txt2bas now. I'll roll out to vscode shortly.

**Comment by NealeTools** [comment]
Ah yes - the import into VSCode also looked truncated - so that's what confirmed to me it was broken (when it wasn't?)

**Comment by remy** [comment]
Okay, all updated, including web site (though make sure you've got `Version: 2024-07-09 18:55` in the bottom right - if not, hit reload and it should clear the service worker cache).

**Comment by NealeTools** [comment]
Just checking: Is/was the export OK?

**Comment by NealeTools** [comment]
Website import works! :-) (Although format of lines >999) is a bit squiffy:
<img width="984" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/4b96317c-36cd-42d1-89d0-ca071fa80d03">

**Comment by NealeTools** [comment]
Local import in VSCode also working now! :-)
<img width="523" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/a2ea5e2b-2019-4939-8b7a-4b39354a424d">
Fantastic! Just need to figure out where the *actual* bug is now (I think it is in ZXOS itself...)

**Comment by NealeTools** [comment]
> lol, the bracket you were seeing was line `40`. <img alt="SCR-20240709-rati" width="1686" src="https://private-user-images.githubusercontent.com/13700/347082003-b9a4f54c-ca81-42db-92b0-f1e018e0dff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NTA0NzYsIm5iZiI6MTcyMDU1MDE3NiwicGF0aCI6Ii8xMzcwMC8zNDcwODIwMDMtYjlhNGY1NGMtY2E4MS00MmRiLTkyYjAtZjFlMDE4ZTBkZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDE4MzYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViY2IyMWZjYjA3MDE3YzhkNWE4MTM1M2NmZWMwNjZhMzA3Y2UyZTA3MTRlYThmZDY5NGY0ODU2MjExNDUyZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B8o4-bAz1cOBtsvIGIOQ-DkGU6t0IIVJJTHlJ2LN3wk">
> 
> I've got the fix for it clipping the last line (pretty sure all files should have been affected… or maybe it was a fluke that it wasn't).
> 
> I'll have to also get the web site synced because I know people do use that as a test, but it's released to in a totally different way.

Q: Where did you get the ZX +3DOS plugin for hexfiend? I can't find it on Github link. 👍

**Comment by remy** [comment]
I wrote it, it's this:

```tcl
little_endian
set checksum 0
requires 0 "504C 5553 3344 4F53"
ascii 8 "signature"
requires 8 "1A 01 00" ;# eof, issue + version
uint8 "soft-eof"
uint8 "issue"
uint8 "version"
uint32 "length incl. header"
section "+3 BASIC Header" {
  uint8 "fileType"
  uint16 "program length"
  uint16 "autostart"
  uint16 "var offset"
  uint8 "unused"
}
bytes 104 "reserved"
uint8 "checksum"
```

**Comment by NealeTools** [comment]
Thanks @remy ! I'm loving using the new #bankfile directive. It makes splitting code between banks entirely trivial.
Such a good workflow. :-) Alongside CSpect, I'm using ExportToBas for saving and syncing (via NextSync), I can push directly to the Next for testing without any manual copying. 🥇
