### ISSUE TITLE
VSCode Extension still doesn't work...

### ISSUE THREAD

**Issue by Andy1966uk** [remy/vscode-nextbasic#9]
Looks like two issues, 1. Programs don;t automatically run any more. CSPECT used to launch and run program, now you have to manually go into NEXTBasic (where you see your program listing#) and RUN it.
2. Assets no longer get ported over to the CSPECT next image... only index.bas gets copied over into the devel folder

**Comment by remy** [comment]
Can you confirm the extension version you're on?

**Comment by remy** [comment]
I've just tested with windows and the latest 1.3.8 extension and the program is autorunning (I've not been able to check assets yet).

*However* I am seeing this bug: #6, so I tested with 

```
10 PRINT "Hello"
20 PRINT "World"
30 GO TO 10
```

**Comment by jsanjose** [comment]
No problem here. The extension copias all files and folders present inside the folder you are running the Basic program.

![image](https://user-images.githubusercontent.com/11646970/83146891-31bc1f00-a0f7-11ea-999b-5317711eb5fb.png)

**Comment by Andy1966uk** [comment]
Not working for me on 1.3.8 or 1.3.9 program don;t autorun and assets aren't copied over, only the program which gets renamed " index.bas"

**Comment by remy** [comment]
Sod. I'm pretty sure the code by itself is sound (as I did a fresh install), but there's something else at play.

Can I ask:

- Are you working on a previously working codebase (I've assumed you are)?
- Do you have the same problems if you try with a new directory and a simple "hello world" file?
- Have you tried removing the entire `/devel` directory on the cspect image (to confirm it's not re-using some old content)?
- If you uninstall and re-install the extension, do you have the same problems (remember to check your settings before you remove)?

I'm not sure that will bring anything up, but it's a start.

**Comment by Andy1966uk** [comment]
Working with previous codebase  yes
New Directory work with autorun and porting assets to image ok
have tried uninstalling and reinstalling extension
Continuing to test on current folders and files now..... will let you know

**Comment by Andy1966uk** [comment]
Old Folder and Files don't work.... will try backing up, deleting and creating new folder and workspace structure, maybe that will work...

**Comment by Andy1966uk** [comment]
Tried renaming folder, resetting and reinstalling Extension, brand new folder and contents worked though, but on all older programs assets don;t get copied over. Also removed the devel folder and all contents....

**Comment by Andy1966uk** [comment]
I have noticed a .vscode folder appears in the new folder though, but is not present in the other folders... could that be it ?

**Comment by remy** [comment]
that's your vscode editor putting that there, but the push process skips over files prefixed with a `.`.

Okay, so we know it's something to do with the setup of your existing codebase and how the extension is using it.

On an older project (that doesn't work), can you open vscode and then from Help->Toggle developer tools, then do the "run with cspect" - see if anything mentions either cspect, hdfmonkey or the nextbasic extension in there?

**Comment by Andy1966uk** [comment]
Good, news, I enabled the development tool and it showed it was trying to copy 96 files over, and hence failed... not sure why it worked last night, but I have been backing up files in same structure, i.e variants of .spr and .map files etc. Anyway I have reduced the file number down and it works.... sorry to waste your time... thx

**Comment by remy** [comment]
Ah, I should really alert when that blocks out - I had noticed my own dev, I'd drop files in random places and accidentally move several gig of files into the cspect image! So I added a check that topped out 50 files. I'll change it so it's not just a silent error but a popup warning (like when export works).

Glad it's sorted :phew:!

**Comment by remy** [comment]
Just to let you know I've added a couple of additional warning messages when things go wrong. The upload (to cspect) limit is set to 50 and if there's more files attempting to copy, it says that it aborted in vscode (the 50 is also user configurable, so you can up this to your liking).

There's also now a warning if export fails due to validation errors and a warning (but still runs) if there's validation errors before a cspect launch.
